# Generated by Django 3.2.5 on 2021-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_name', models.CharField(max_length=20)),
            ],
        ),
    ]
